In [4]:
!pip install python_speech_features fastdtw


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.4/133.4 kB 2.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for fastdtw: filename=fastdtw-0.3.4-cp310-cp310-linux_x86_64.whl size=512710 sha256=9813598ebc43b3d2d1a563067875a08a30e5004573720d439795c2b77a81ce47
  Stored in directory: /root/.cache/pip/wheels/73/c8/f7/c25448dab74c3acf4848bc25d513c736bb93910277e1528ef4
Successfully built fastdtw


In [5]:
import numpy as np
from fastdtw import fastdtw
import math
from scipy.spatial.distance import euclidean, sqeuclidean, cosine, correlation, chebyshev, cityblock, minkowski

template = np.array([[1,1,3,6,12], [1,1,2,5,11], [3,3,3,3,3]])
input_arr = np.array([[1,2,11], [1,3,12], [3,3,3]])


def compute_cost_matrix(input_array, template):
    distance_matrix = np.zeros((len(template), len(input_array)))
    for i in range(len(distance_matrix)):
        for j in range(len(distance_matrix[0])):
            distance_matrix[i][j] = eucledian(input_array[j], template[i])

    return distance_matrix

def eucledian(a, b):
    total = 0
    for i in range(len(a)):
        total += (a[i]-b[i])**2
    return math.sqrt(total)

def compute_accumulated_cost_matrix(C):
    N = C.shape[0]
    M = C.shape[1]
    D = np.zeros((N, M))
    D[0, 0] = C[0, 0]
    for n in range(1, N):
        D[n, 0] = D[n-1, 0] + C[n, 0]
    for m in range(1, M):
        D[0, m] = D[0, m-1] + C[0, m]
    for n in range(1, N):
        for m in range(1, M):
            D[n, m] = C[n, m] + min(D[n-1, m], D[n, m-1], D[n-1, m-1])
    return D

C = compute_cost_matrix(input_array=input_arr.T, template=template.T)
D =  compute_accumulated_cost_matrix(C)
print('Accumulated cost matrix D =', D, sep='\n')
print('DTW distance DTW(X, Y) =', D[-1, -1])

print("DTW calculation using library:", fastdtw(input_arr.T, template.T, dist=euclidean))


Accumulated cost matrix D =
[[ 0.          2.23606798 17.10213672]
 [ 0.          2.23606798 17.10213672]
 [ 2.23606798  1.41421356 14.22046204]
 [ 8.63919221  5.88634952 10.01653883]
 [23.50526096 18.69259799  7.30056308]]
DTW distance DTW(X, Y) = 7.3005630797457695
DTW calculation using library: (7.3005630797457695, [(0, 0), (0, 1), (1, 2), (1, 3), (2, 4)])


In [14]:
from python_speech_features import mfcc
from python_speech_features import logfbank
import scipy.io.wavfile as wav
import os

folder_path = './dictionary/'
template = []
if os.path.exists(folder_path) and os.path.isdir(folder_path):
    # List all files in the folder
    files = os.listdir(folder_path)

    # Iterate through the files
    for file_name in files:
        # You can process each file here, for example, print the file name
        print(file_name)
        (rate,sig) = wav.read(folder_path + file_name)
        print("signal length and channel : ", sig.shape )
        mfcc_feat = mfcc(sig,rate,nfilt = 39,numcep = 39,nfft =2048)

        print("feature extraction length and channel : ", mfcc_feat.shape)
        template.append([file_name[:-4],mfcc_feat])

tugas.wav
signal length and channel :  (61056, 2)
feature extraction length and channel :  (253, 39)
merupakan.wav
signal length and channel :  (70272, 2)
feature extraction length and channel :  (292, 39)
suara2.wav
signal length and channel :  (70272, 2)
feature extraction length and channel :  (292, 39)
kuliah.wav
signal length and channel :  (81792, 2)
feature extraction length and channel :  (340, 39)
kecil.wav
signal length and channel :  (56448, 2)
feature extraction length and channel :  (234, 39)
ini.wav
signal length and channel :  (61056, 2)
feature extraction length and channel :  (253, 39)
halo.wav
signal length and channel :  (56448, 2)
feature extraction length and channel :  (234, 39)
pemrosesan.wav
signal length and channel :  (72576, 2)
feature extraction length and channel :  (301, 39)


In [28]:
folder_path = './test/rafli/'
test = []
if os.path.exists(folder_path) and os.path.isdir(folder_path):
    # List all files in the folder
    files = os.listdir(folder_path)

    # Iterate through the files
    for file_name in files:
        # You can process each file here, for example, print the file name
        print(file_name)
        (rate,sig) = wav.read(folder_path + file_name)
        print("signal length and channel : ", sig.shape )
        mfcc_feat = mfcc(sig,rate,nfilt = 39,numcep = 39,nfft =2048)

        print("feature extraction length and channel : ", mfcc_feat.shape)
        test.append([file_name[:-4],mfcc_feat])


tugas.wav
signal length and channel :  (67584,)
feature extraction length and channel :  (140, 39)
merupakan.wav
signal length and channel :  (81920,)
feature extraction length and channel :  (170, 39)
kuliah.wav
signal length and channel :  (73728,)
feature extraction length and channel :  (153, 39)
kecil.wav
signal length and channel :  (73728,)
feature extraction length and channel :  (153, 39)
ini.wav
signal length and channel :  (73728,)
feature extraction length and channel :  (153, 39)
halo.wav
signal length and channel :  (71680,)
feature extraction length and channel :  (148, 39)
suara.wav
signal length and channel :  (60416,)
feature extraction length and channel :  (125, 39)
pemrosesan.wav
signal length and channel :  (82944,)
feature extraction length and channel :  (172, 39)


In [17]:
folder_path = './test/ronggur/'
if os.path.exists(folder_path) and os.path.isdir(folder_path):
    # List all files in the folder
    files = os.listdir(folder_path)

    # Iterate through the files
    for file_name in files:
        # You can process each file here, for example, print the file name
        print(file_name)
        (rate,sig) = wav.read(folder_path + file_name)
        print("signal length and channel : ", sig.shape )
        mfcc_feat = mfcc(sig,rate,nfilt = 39,numcep = 39,nfft =2048)

        print("feature extraction length and channel : ", mfcc_feat.shape)
        test.append([file_name[:-4],mfcc_feat])


tugas.wav
signal length and channel :  (73728, 2)
feature extraction length and channel :  (306, 39)
merupakan.wav
signal length and channel :  (94208, 2)
feature extraction length and channel :  (392, 39)
kuliah.wav
signal length and channel :  (82944, 2)
feature extraction length and channel :  (345, 39)
kecil.wav
signal length and channel :  (93184, 2)
feature extraction length and channel :  (387, 39)
ini.wav
signal length and channel :  (90112, 2)
feature extraction length and channel :  (374, 39)
halo.wav
signal length and channel :  (140288, 2)
feature extraction length and channel :  (584, 39)
suara.wav
signal length and channel :  (87040, 2)
feature extraction length and channel :  (362, 39)
pemrosesan.wav
signal length and channel :  (93184, 2)
feature extraction length and channel :  (387, 39)


In [29]:
test[0:3]

[['tugas',
  array([[ 1.09103200e+01, -1.21212583e+01,  2.12327858e+01, ...,
          -9.97352069e-01, -1.17548641e+00,  1.81987293e+00],
         [ 1.14589629e+01, -1.42562940e+01,  1.86311900e+01, ...,
          -6.81085007e-02, -1.84428232e+00,  1.20500972e+00],
         [ 1.14927921e+01, -1.63281452e+01,  1.70746797e+01, ...,
           1.02877283e+00, -1.05726539e+00, -5.92777396e-01],
         ...,
         [ 1.19302725e+01, -1.58212257e+01,  3.81857370e+00, ...,
           7.68235379e-01, -5.43968403e-02, -2.73609897e+00],
         [ 1.14781122e+01, -1.50112499e+01,  5.56490744e+00, ...,
          -8.79008476e-03, -1.13668011e+00, -2.91614600e+00],
         [ 9.99890089e+00, -1.50721779e+01, -1.34266695e+00, ...,
          -2.93259797e-01,  3.38853882e-01, -1.01645271e-01]])],
 ['merupakan',
  array([[ 10.96235063,  -9.92180503,  18.38242208, ...,  -3.0618727 ,
           -5.48218273,   1.89419425],
         [ 11.6347387 , -12.13760129,  14.47704224, ...,  -1.74282057,
        

In [42]:
for i in test:
    bestGuessClass = template[0][0]
    bestScore = 99999999.0
    for j in template:
      C = compute_cost_matrix(input_array=i[1], template=j[1])
      D =  compute_accumulated_cost_matrix(C)
      # print(D[-1, -1])
      if (bestScore > D[-1, -1]).any():
        bestScore = D[-1, -1]
        bestGuessClass = j[0]
    print("groundtruth :", i[0])
    print("Predicted : ", bestGuessClass)
    print("Score : ", bestScore)
    print("------------------")


groundtruth : tugas
Predicted :  halo
Score :  26707.485299908898
------------------
groundtruth : merupakan
Predicted :  halo
Score :  27221.776847280486
------------------
groundtruth : kuliah
Predicted :  halo
Score :  26456.12387813376
------------------
groundtruth : kecil
Predicted :  ini
Score :  26602.40984703177
------------------
groundtruth : ini
Predicted :  halo
Score :  28081.678683637438
------------------
groundtruth : halo
Predicted :  halo
Score :  28165.0635320707
------------------
groundtruth : suara
Predicted :  halo
Score :  25544.781633270613
------------------
groundtruth : pemrosesan
Predicted :  halo
Score :  26707.89421025205
------------------
